export const GubnType = {
  gangnam: { name: '강남', code: '23' },
  gangdong: { name: '강동', code: '25' },
  gangbuk: { name: '강북', code: '09' },
  gangseo: { name: '강서', code: '16' },
  gwanak: { name: '관악', code: '21' },
  gwangjin: { name: '광진', code: '05' },
  guro: { name: '구로', code: '17' },
  geumcheon: { name: '금천', code: '18' },
  nowon: { name: '노원', code: '11' },
  dobong: { name: '도봉', code: '10' },
  dongdaemun: { name: '동대문', code: '06' },
  dongjak: { name: '동작', code: '20' },
  mapo: { name: '마포', code: '14' },
  seocho: { name: '서초', code: '22' },
  seodaemun: { name: '서대문', code: '13' },
  seongbuk: { name: '성북', code: '08' },
  seongdong: { name: '성동', code: '04' },
  songpa: { name: '송파', code: '24' },
  yangcheon: { name: '양천', code: '15' },
  yeongdeungpo: { name: '영등포', code: '19' },
  yongsan: { name: '용산', code: '03' },
  eunpyeong: { name: '은평', code: '12' },
  jongno: { name: '종로', code: '01' },
  jung: { name: '중', code: '02' },
  jungnang: { name: '중랑', code: '07' },
};
