export const Gubntype = {
    Gangnam : 1,
    Gangdong : 2,
    Gangbuk : 3,
    Gangseo : 4,
    Gwanak  : 5,
    Gwangjin  : 6,
    Guro  : 7,
    Geumcheon : 8,
    Nowon   : 9,
    Dobong  : 10,
    Dongdaemun   : 11,
    Dongjak : 12,
    Mapo   : 13,
    Seocho   : 14,
    Seodaemun :15,
    Seongbuk   : 16,
    Seongdong : 17,
    Songpa : 18,
    Yangcheon : 19,
    Yeongdeungpo    : 20,
    Yongsan : 21,
    Eunpyeong    : 22,
    Jongno : 23,
    Jung   : 24,
    Jungnang : 25
}